# code coverage run
name: Coverage-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    include:
    - '*'

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 0
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  __SuppressAnsiEscapeSequences: 1

resources:
- repo: self
  clean: true

stages:
- stage: CoverageStage
  displayName: Build and coverage for Linux
  jobs:
  - job: linux_nonelevated_coverage
    pool:
      vmImage: ubuntu-18.04
    displayName: Gather nonelevated coverage for Linux

    steps:
    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBootstrap
      displayName: Boot strap builds and tools

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBuild
      displayName: build powershell

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageRun -tType nonelevated
      displayName: Collect non-elevated coverage
      condition: succeededOrFailed()
      continueOnError: true

  - job: linux_elevated_coverage
    pool:
      vmImage: ubuntu-18.04
    displayName: Gather elevated coverage for Linux

    steps:
    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBootstrap
      displayName: Boot strap builds and tools

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBuild
      displayName: build powershell

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageRun -tType elevated
      displayName: Collect elevated coverage
      condition: succeededOrFailed()
      continueOnError: true

  - job: macos_nonelevated_coverage
    pool:
      vmImage: macos-latest
    displayName: Gather nonelevated coverage for MacOS

    steps:
    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBootstrap
      displayName: Boot strap builds and tools

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBuild
      displayName: build powershell

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageRun -tType nonelevated
      displayName: Collect non-elevated coverage
      condition: succeededOrFailed()
      continueOnError: true

  - job: macos_elevated_coverage
    pool:
      vmImage: macos-latest
    displayName: Gather elevated coverage for MacOS

    steps:
    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBootstrap
      displayName: Boot strap builds and tools

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBuild
      displayName: build powershell

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageRun -tType elevated
      displayName: Collect elevated coverage
      condition: succeededOrFailed()
      continueOnError: true
