# code coverage run
name: Coverage-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    include:
    - '*'

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 0
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  __SuppressAnsiEscapeSequences: 1

resources:                              
- repo: self                                       
  clean: true                                                                                                

stages:                   
- stage: Linux
  displayName: Build and coverage for Linux
  jobs:
  - job: linux_coverage
    pool:
      vmImage: ubuntu-16.04
    displayName: Gather coverage for Linux 

    steps:
    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBootstrap
      displayName: Boot strap builds and tools

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageBuild
      displayName: build powershell

    - pwsh: |
        Import-Module ./tools/cc.psm1
        Start-CoverageRun
      displayName: Collect coverage
